# tasks file for db
---
- name: Show info about the env this host belongs to
  debug:
    msg: "This host is in the {{ env }} environment!!!"

- import_tasks: install_mongo.yml
- import_tasks: config_mongo.yml
